# Generated by Django 5.0.3 on 2024-04-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina_curso',
            old_name='nome',
            new_name='disciplina',
        ),
        migrations.RenameField(
            model_name='ocupacao',
            old_name='coordenador',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='periodo',
            old_name='primeiro_periodo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='tipo_avaliacao',
            old_name='lista_exercicios',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='periodo',
            new_name='turno',
        ),
        migrations.RemoveField(
            model_name='ocupacao',
            name='diretor',
        ),
        migrations.RemoveField(
            model_name='ocupacao',
            name='estudante',
        ),
        migrations.RemoveField(
            model_name='ocupacao',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='segundo_periodo',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='coord',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='estudantes',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='professores',
        ),
        migrations.RemoveField(
            model_name='tipo_avaliacao',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='tipo_avaliacao',
            name='prova',
        ),
        migrations.RemoveField(
            model_name='tipo_avaliacao',
            name='trabalho',
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
